export const CREATE_GOAL = 'CREATE_GOAL';
export const CREATE_GOAL_SUCCESS = 'CREATE_GOAL_SUCCESS';
export const CREATE_GOAL_FAILED = 'CREATE_GOAL_FAILED';

export const FETCH_GOAL = 'FETCH_GOAL';
export const FETCH_GOAL_SUCCESS = 'FETCH_GOAL_SUCCESS';
export const FETCH_GOAL_FAILED = 'FETCH_GOAL_FAILED';
export const FETCH_GOAL_REFRESH = 'FETCH_GOAL_REFRESH';

export const FETCHSHOW_GOAL = 'FETCHSHOW_GOAL';
export const FETCHSHOW_GOAL_SUCCESS = 'FETCHSHOW_GOAL_SUCCESS';
export const FETCHSHOW_GOAL_FAILED = 'FETCHSHOW_GOAL_FAILED';

export const DELETE_GOAL = 'DELETE_GOAL';
export const DELETE_GOAL_SUCCESS = 'DELETE_GOAL_SUCCESS';
export const DELETE_GOAL_FAILED = 'DELETE_GOAL_FAILED';
